version: "3.7"

services:
  server:
    image: testauslink-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - dev-database
    environment:
      - DATABASE_URL=postgres://testauslink:testauslink@dev-database:5432/testauslink
      - PORT=3000
      - RATELIMIT_WINDOW=60
      - RATELIMIT_MAX=10
  dev-database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: testauslink
      POSTGRES_PASSWORD: testauslink
      POSTGRES_DB: testauslink